### ISSUE TITLE
Help: Handling \n

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [farling42/fvtt-export-markdown#7]
Hi Farling, 

I've been bashing my head against this one for about 2 weeks now. Nothing I try results in success so hoping you can help. 
Note: I am not that technical, stumbling my way through this!

**Objective:** I am trying to create a Handlebar that can handle Monsters exporting from Foundry. 

**Issue:** Some of the fields contain a \n. I have tried all sorts of solutions and created handlebars to handle the '\n' but so far I have had 0% at removing the breaklines. The breakline instantly breaks the rendering of the statblock in Obsidian. 

**Example Source Data**
[Blood Ooze.md](https://github.com/farling42/fvtt-export-markdown/files/13233754/Blood.Ooze.md)

**Example of Problematic Data**
```
      "system": {
        "description": {
          "gm": "",
          "value": "<p><strong>Trigger</strong> The blood ooze is damaged by a piercing or slashing attack.</p>\n<hr />\n<p><strong>Effect</strong> The blood ooze forms a clot around the wound, reducing the damage taken by 5 (to a minimum of 0).</p>"
```

**My current handlebar template:** 
[Uploading PF2e_Foundry_Monster_Handlebar_v1.1_Foundry.md…]()

**Pre-Requirements**
I am using Kgar's More-Handlebars-Helpers in the process. 
 https://github.com/kgar/foundry-vtt-more-handlebars-helpers/releases/latest/download/module.json

**Example Handlebar Template:** 
Here are some of the things I have tried. 
```
	raw: {{system.description.value}}
	raw: {{{system.description.value}}}
	version1: {{more-handlebars-helpers-replaceAll system.description.value '\n' ''}}
	version1: {{more-handlebars-helpers-replaceAll system.description.value '\\n' ''}}
	Version2: {{more-handlebars-helpers-replaceAll system.description.value '\\n' '' }}
	Version2: {{{more-handlebars-helpers-replaceAll system.description.value '\\n' '' }}}
	version1: {{more-handlebars-helpers-replaceAll system.description.value '</p>\n<hr />\n<p>' ''}}
	Version4: {{more-handlebars-helpers-sanitize system.description.value}}
	Version5: {{{more-handlebars-helpers-sanitize system.description.value}}}
```

I have tried this through both the JSON/CSV Importer on the Obsidian side and the Foundry Markdown Exporter. In both situations the handlebar does not seem to recognise the '\n' is there. I get different variations in the results above but in all cases the breakline exists in the output. 

**Example output:**
```
	version1: <p><strong>Trigger</strong> The blood ooze is damaged by a piercing or slashing attack.</p>
<hr />
<p><strong>Effect</strong> The blood ooze forms a clot around the wound, reducing the damage taken by 5 (to a minimum of 0).</p>
```

```
	Version4: Trigger The blood ooze is damaged by a piercing or slashing attack.

Effect The blood ooze forms a clot around the wound, reducing the damage taken by 5 (to a minimum of 0).
```

Is it possible the \n is processed before the handlebar is applied? That's what it feels like.

**Comment by farling42** [comment]
You can see in your final example outputs that the string "<hr />" is the reason the blank line is being put in. So you could try replacing that string instead. On 2 Nov 2023 03:13, ObsidianTTRPGProject ***@***.***> wrote:
Hi Farling,
I've been bashing my head against this one for about 2 weeks now. Nothing I try results in success so hoping you can help.
Note: I am not that technical, stumbling my way through this!
Objective: I am trying to create a Handlebar that can handle Monsters exporting from Foundry.
Issue: Some of the fields contain a \n. I have tried all sorts of solutions and created handlebars to handle the '\n' but so far I have had 0% at removing the breaklines. The breakline instantly breaks the rendering of the statblock in Obsidian.
Example Source Data
Blood Ooze.md
Pre-Requirements
I am using Kgar's More-Handlebars-Helpers in the process.
https://github.com/kgar/foundry-vtt-more-handlebars-helpers/releases/latest/download/module.json
Example Handlebar Template:
Here are some of the things I have tried.
raw: {{system.description.value}}
raw: {{{system.description.value}}}
version1: {{more-handlebars-helpers-replaceAll system.description.value '\n' ''}}
version1: {{more-handlebars-helpers-replaceAll system.description.value '\n' ''}}
Version2: {{more-handlebars-helpers-replaceAll system.description.value '\n' '' }}
Version2: {{{more-handlebars-helpers-replaceAll system.description.value '\n' '' }}}
version1: {{more-handlebars-helpers-replaceAll system.description.value '\n\n' ''}}
Version4: {{more-handlebars-helpers-sanitize system.description.value}}
Version5: {{{more-handlebars-helpers-sanitize system.description.value}}}
I have tried this through both the JSON/CSV Importer on the Obsidian side and the Foundry Markdown Exporter. In both situations the handlebar does not seem to recognise the '\n' is there. I get different variations in the results above but in all cases the breakline exists in the output.
Example output:
	version1: <p><strong>Trigger</strong> The blood ooze is damaged by a piercing or slashing attack.</p>
<hr />
<p><strong>Effect</strong> The blood ooze forms a clot around the wound, reducing the damage taken by 5 (to a minimum of 0).</p>

	Version4: Trigger The blood ooze is damaged by a piercing or slashing attack.

Effect The blood ooze forms a clot around the wound, reducing the damage taken by 5 (to a minimum of 0).

Is it possible the \n is processed before the handlebar is applied? That's what it feels like.

**Comment by ObsidianTTRPGProject** [comment]
> You can see in your final example outputs that the string "<hr />" is the reason the blank line is being put in. 

I've tried a few variations of removing that with no luck so far. Here's the latest attempt. 

```
abilities_mid:{{#each items}}{{#if (eq system.category "defensive")}}
  - name: "{{name}} ({{system.actions.value}}{{system.actionType.value}})"
    desc: {{more-handlebars-helpers-sanitize (more-handlebars-helpers-replaceAll (more-handlebars-helpers-replaceAll system.description.value '\n' '') '<hr />' '')}}{{/if}}{{/each}}
```

This results in: 

```
abilities_mid:
  - name: "Blood Pool (passive)"
    desc: Whenever a creature adjacent to a blood ooze takes bleed damage, the blood ooze regains an amount of Hit Points equal to the damage dealt.
  - name: "Clot (reaction)"
    desc: Trigger The blood ooze is damaged by a piercing or slashing attack.

Effect The blood ooze forms a clot around the wound, reducing the damage taken by 5 (to a minimum of 0).
```

from source

```
      "system": {
        "description": {
          "gm": "",
          "value": "<p><strong>Trigger</strong> The blood ooze is damaged by a piercing or slashing attack.</p>\n<hr />\n<p><strong>Effect</strong> The blood ooze forms a clot around the wound, reducing the damage taken by 5 (to a minimum of 0).</p>"
        },
```

**Comment by ObsidianTTRPGProject** [comment]
Here's another variant
```
abilities_mid:{{#each items}}{{#if (eq system.category "defensive")}}
  - name: "{{name}} ({{system.actions.value}}{{system.actionType.value}})"
    desc: {{more-handlebars-helpers-sanitize (more-handlebars-helpers-replaceAll system.description.value '\n<hr />\n' '')}}{{/if}}{{/each}}
```

```
abilities_mid:
  - name: "Blood Pool (passive)"
    desc: Whenever a creature adjacent to a blood ooze takes bleed damage, the blood ooze regains an amount of Hit Points equal to the damage dealt.
  - name: "Clot (reaction)"
    desc: Trigger The blood ooze is damaged by a piercing or slashing attack.

Effect The blood ooze forms a clot around the wound, reducing the damage taken by 5 (to a minimum of 0).
```
